import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

const mandai = localFont({
  src: [
    {
      path: "../../public/fonts/MandaiValueSerif-Bold.ttf",
      weight: "bold",
    },
    {
      path: "../../public/fonts/MandaiValueSerif-Regular.ttf",
      weight: "normal",
    },
  ],
  variable: "--font-mandai",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${mandai.variable}`}>
        {children}
        <Toaster />
        <Analytics />
      </body>
    </html>
  );
}
